/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mokleters
 */
public class aritmatika extends javax.swing.JFrame {
    String jns="";
    int jmlh;
    /**
     * Creates new form aritmatika
     */
    public aritmatika() {
        initComponents();
        jns = null;
        panel.setVisible(false);
        bil1.setVisible(false);
                bil2.setVisible(false);
                bil3.setVisible(false);
                bil4.setVisible(false);
                b1.setVisible(false);
                b3.setVisible(false);
                b3.setVisible(false);
                b4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        bil1 = new javax.swing.JTextField();
        bil2 = new javax.swing.JTextField();
        bil3 = new javax.swing.JTextField();
        bil4 = new javax.swing.JTextField();
        b3 = new javax.swing.JLabel();
        ket = new javax.swing.JLabel();
        jumlah2 = new javax.swing.JComboBox<>();
        b1 = new javax.swing.JLabel();
        hitung = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        hasil = new javax.swing.JTextField();
        b4 = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jenis = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel3.setLayout(null);

        panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OPERASI", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        panel.setLayout(null);

        bil1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bil1.setForeground(new java.awt.Color(255, 0, 102));
        bil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil1ActionPerformed(evt);
            }
        });
        panel.add(bil1);
        bil1.setBounds(180, 140, 210, 40);

        bil2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bil2.setForeground(new java.awt.Color(255, 0, 102));
        panel.add(bil2);
        bil2.setBounds(180, 190, 210, 40);

        bil3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bil3.setForeground(new java.awt.Color(255, 0, 102));
        panel.add(bil3);
        bil3.setBounds(180, 240, 210, 40);

        bil4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bil4.setForeground(new java.awt.Color(255, 0, 102));
        panel.add(bil4);
        bil4.setBounds(180, 290, 210, 40);

        b3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        b3.setText("Bilangan 3");
        panel.add(b3);
        b3.setBounds(20, 240, 140, 30);

        ket.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        panel.add(ket);
        ket.setBounds(70, 20, 170, 40);

        jumlah2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jumlah2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--PILIH--", "2", "3", "4" }));
        jumlah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlah2ActionPerformed(evt);
            }
        });
        panel.add(jumlah2);
        jumlah2.setBounds(180, 80, 210, 40);

        b1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        b1.setText("Bilangan 1");
        panel.add(b1);
        b1.setBounds(20, 140, 150, 30);

        hitung.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hitung.setText("HITUNG");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        panel.add(hitung);
        hitung.setBounds(530, 160, 110, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Jumlah Bilangan");
        panel.add(jLabel10);
        jLabel10.setBounds(20, 80, 150, 40);

        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });
        panel.add(hasil);
        hasil.setBounds(460, 210, 250, 120);

        b4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        b4.setText("Bilangan 4");
        panel.add(b4);
        b4.setBounds(20, 290, 140, 30);

        b2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        b2.setText("Bilangan 2");
        panel.add(b2);
        b2.setBounds(20, 190, 130, 30);

        jPanel3.add(panel);
        panel.setBounds(30, 100, 730, 430);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("PROGAM ARITMATIKA");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(330, 0, 190, 50);

        jenis.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jenis.setForeground(new java.awt.Color(51, 51, 51));
        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--PILIH--", "penjumlahan", "pengurangan", "perkalian", "pembagian" }));
        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });
        jPanel3.add(jenis);
        jenis.setBounds(210, 60, 170, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(20, 0, 760, 530);

        setBounds(0, 0, 815, 594);
    }// </editor-fold>//GEN-END:initComponents

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
        // TODO add your handling code here:
        setJenis();
    }//GEN-LAST:event_jenisActionPerformed
public void setJenis(){
            if( jenis.getSelectedItem().equals("penjumlahan")){
                jns = "penjumlahan";
                ket.setText("penjumlahan");
                panel.setVisible(true);
                jumlah2.setEnabled(true);
        }
            else if( jenis.getSelectedItem().equals("pengurangan")){
                jns = "pengurangan";
                ket.setText("pengurangan");
                panel.setVisible(true);
                jumlah2.setEnabled(true);
        }
            else if( jenis.getSelectedItem().equals("perkalian")){
                jns = "perkalian";
                ket.setText("perkalian");
                panel.setVisible(true);
                jumlah2.setEnabled(true);
        }
            else if( jenis.getSelectedItem().equals("pembagian")){
                jns = "pembagian";
                ket.setText("pembagian");
                panel.setVisible(true);
                jumlah2.setEnabled(true);
        }
            else{
                jns = null;
                panel.setVisible(false);
        }
    }
    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
        Double hsl;
        Double a1,a2,a3,a4;

        a1 = Double.parseDouble(bil1.getText().toString());
        a2 = Double.parseDouble(bil2.getText().toString());

        if(jns.equals("penjumlahan")){
            if(jmlh == 2){
                hsl = a1 + a2;
                hasil.setText(""+ a1 + " + " + a2 + " = " + hsl);
            }
            if(jmlh == 3){
                a3 = Double.parseDouble(bil3.getText().toString());
                hsl = a1 + a2 + a3;
                hasil.setText(""+ a1 + " + " + a2 + " + " + a3 + " = " + hsl);
            }
            if(jmlh == 4){
                a3 = Double.parseDouble(bil3.getText().toString());
                a4 = Double.parseDouble(bil4.getText().toString());
                hsl = a1 + a2 + a3 + a4;
                hasil.setText(""+ a1 + " + " + a2 + " + " + a3 + "+ " + a4 + " = " + hsl);
            }
        }
        else if(jns.equals("pengurangan")){
            if(jmlh == 2){
                hsl = a1 - a2;
                hasil.setText(""+ a1 + " - " + a2 + " = " + hsl);
            }
            if(jmlh == 3){
                a3 = Double.parseDouble(bil3.getText().toString());
                hsl = a1 - a2 - a3;
                hasil.setText(""+ a1 + " - " + a2 + " - " + a3 + " = " + hsl);
            }
            if(jmlh == 4){
                a3 = Double.parseDouble(bil3.getText().toString());
                a4 = Double.parseDouble(bil4.getText().toString());
                hsl = a1 - a2 - a3 - a4;
                hasil.setText(""+ a1 + " - " + a2 + " - " + a3 + " - " + a4 + " = " + hsl);
            }
        }
        else if(jns.equals("perkalian")){
            if(jmlh == 2){
                hsl = a1 * a2;
                hasil.setText(""+ a1 + " x " + a2 + " = " + hsl);
            }
            if(jmlh == 3){
                a3 = Double.parseDouble(bil3.getText().toString());
                hsl = a1 * a2 * a3;
                hasil.setText(""+ a1 + " x " + a2 + " x " + a3 + " = " + hsl);
            }
            if(jmlh == 4){
                a3 = Double.parseDouble(bil3.getText().toString());
                a4 = Double.parseDouble(bil4.getText().toString());
                hsl = a1 * a2 * a3 * a4;
                hasil.setText(""+ a1 + " x " + a2 + " x " + a3 + " x " + a4 + " = " + hsl);
            }
        }
        else if(jns.equals("pembagian")){
            if(jmlh == 2){
                hsl = a1 / a2;
                hasil.setText(""+ a1 + " / " + a2 + " = " + hsl);
            }
            if(jmlh == 3){
                a3 = Double.parseDouble(bil3.getText().toString());
                hsl = a1 / a2 / a3;
                hasil.setText(""+ a1 + " / " + a2 + " / " + a3 + " = " + hsl);
            }
            if(jmlh == 4){
                a3 = Double.parseDouble(bil3.getText().toString());
                a4 = Double.parseDouble(bil4.getText().toString());
                hsl = a1 / a2 / a3 / a4;
                hasil.setText(""+ a1 + " / " + a2 + " / " + a3 + " / " + a4 + " = " + hsl);
            }
        }
    }//GEN-LAST:event_hitungActionPerformed

    private void jumlah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlah2ActionPerformed
        // TODO add your handling code here:
        getJumlah();
    }//GEN-LAST:event_jumlah2ActionPerformed
public void getJumlah(){
        if( jumlah2.getSelectedItem().equals("2")){
                bil1.setVisible(true);
                bil2.setVisible(true);
                bil3.setVisible(false);
                bil4.setVisible(false);
                b1.setVisible(true);
                b2.setVisible(true);
                b3.setVisible(false);
                b4.setVisible(false);
                jmlh = 2;
        }
        else if( jumlah2.getSelectedItem().equals("3")){
                bil1.setVisible(true);
                bil2.setVisible(true);
                bil3.setVisible(true);
                bil4.setVisible(false);
                b1.setVisible(true);
                b2.setVisible(true);
                b3.setVisible(true);
                b4.setVisible(false);
                jmlh = 3;
        }
        else if( jumlah2.getSelectedItem().equals("4")){
                bil1.setVisible(true);
                bil2.setVisible(true);
                bil3.setVisible(true);
                bil4.setVisible(true);
                b1.setVisible(true);
                b2.setVisible(true);
                b3.setVisible(true);
                b4.setVisible(true);
                jmlh = 4;
        }
        else{
                bil1.setVisible(false);
                bil2.setVisible(false);
                bil3.setVisible(false);
                bil4.setVisible(false);
                b1.setVisible(false);
                b2.setVisible(false);
                b3.setVisible(false);
                b4.setVisible(false);
                
        }
    }
    private void bil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bil1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aritmatika().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b3;
    private javax.swing.JLabel b4;
    private javax.swing.JTextField bil1;
    private javax.swing.JTextField bil2;
    private javax.swing.JTextField bil3;
    private javax.swing.JTextField bil4;
    private javax.swing.JTextField hasil;
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JComboBox<String> jumlah;
    private javax.swing.JComboBox<String> jumlah1;
    private javax.swing.JComboBox<String> jumlah2;
    private javax.swing.JLabel ket;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
